### ISSUE TITLE
BulkInsert with nullable propery error

### ISSUE THREAD

**Issue by hanc2006** [zzzprojects/Dapper-Plus#1]
Hi,
I try to update one table with this code
```

DapperPlusManager.Entity<BookingRequest>().Table("BookingRequest").Identity(x => x.Id);
                UnitOfWork.Context.Database.Connection.Open();
                UnitOfWork.Context.Database.Connection.BulkInsert(booking)
                                                       .AlsoBulkInsert(b => b.BookingRequestResults);
                UnitOfWork.Context.Database.Connection.Close();
```

But with no success. The framework ask me to set one null-able integer property inside the class BookingRequest. But must be empty.

**Comment by zzzprojects** [comment]
Thank you for reporting.

Can you post the error thrown by the application and the stack trace if possible? It will help us to identify the error.

**Comment by zzzprojects** [comment]
Hello Hanc2006,

We didn't receive anything from your part yet. Is it possible to post the stack trace?

**Comment by hanc2006** [comment]
Hello,
Yes of course. This week I am in holiday, when I come back I send you the
stack trace

**Comment by zzzprojects** [comment]
Hello @hanc2006,

We still have not received anything yet.

Please let me know if you have no time, for now, to help us with this issue. We will simply close the Issues until you find some time.

Best Regards,

Jonathan

**Comment by hanc2006** [comment]
Hi jonathan
You can close this issue for now. I still busy with another project.
Sorry...

King regard
Daniele

**Comment by zzzprojects** [comment]
No problem, I fully understand this. Feel free to open a new issue or reopen this one when you have time to work again on it.

Best Regards,

Jonathan
