### ISSUE TITLE
DapperPlusManager not ignoring Field in Oracle database.

### ISSUE THREAD

**Issue by PedroHFranco** [zzzprojects/Dapper-Plus#10]
Hello,
I'm making an Ignore field, but it not working...

The ignore is for a Oracle Database.

This is the Ignore and the update:

```
DapperPlusManager.Entity<Plugins.Utils.Model.Source.AgriBussines.PEDSENHA>().Ignore(c => c.SolicitacaoAutorizacaoId);
source.UpdateSource(resultTarget);
DapperPlusManager.MapperCache.Clear();
```
The class:

```
namespace Plugins.Utils.Model.Source.AgriBussines
{
    public class PEDSENHA : BaseSource
    {
        public string SolicitacaoAutorizacaoId { get; set; }
        public int CODI_EMP { get; set; }
        public string CODI_SEN { get; set; }
        public string SENH_SEN { get; set; }
        public DateTime DATA_SEN { get; set; }
    }
}

```
And this is the update method:

```
 public static void UpdateSource<T>(this IDbConnection connection, IList<T> result) where T : BaseSource
        {
            using (var transaction = connection.BeginTransaction(IsolationLevel.ReadCommitted))
            {
                try
                {
                    transaction.BulkUpdate(result);
                    transaction.Commit();
                }
                catch (Exception e)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"{result.GetType()} - {e.Message}");
                    Console.ResetColor();
                    transaction.Rollback();
                    throw;
                }
            }
        }
```

I'm gotting this error:

Message : 

> Missing: SolicitacaoAutorizacaoId

StackTrace: 

>   em Z.BulkOperations.BulkOperation.()
>    em ..(BulkOperation )
>    em Z.BulkOperations.BulkOperation.BulkUpdate()
>    em Z.Dapper.Plus.DapperPlusAction.Execute()
>    em Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
>    em Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
>    em Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
>    em Z.Dapper.Plus.DapperPlusExtensions.BulkUpdate[T](IDbTransaction transaction, String mapperKey, T item, Func`2[] selectors)
>    em Z.Dapper.Plus.DapperPlusExtensions.BulkUpdate[T](IDbTransaction transaction, T item, Func`2[] selectors)
>    em Plugins.Utils.Extensions.CommandExtensions.UpdateSource[T](IDbConnection connection, IList`1 result) na D:\Projetos\API-Cloud\etl\Plugins.Utils\Extensions\CommandExtensions.cs:linha 188
>    em SolicitacoesAutorizacao.AgriBusiness.PEDSENHA.JobSolicitacoesAutorizacao.Execute(IJobExecutionContext context)

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

I believe we already started to investigate this issue last week.

I will give you an update later today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @PedroHFranco ,

We tested it and that working fine, however, we have some hypothesis about what could cause this.

This is probably not an issue with the Ignore method but because multiple types are used in the same list.

When this happens, the list is considered as the type of the first item.

By example:

```csharp
var resultTarget = new List<BaseSource>();
resultTarget.Add(new BaseSource());
resultTarget.Add(new PEDSENHA());
```

Will cast all the list as `BaseSource` and will use the `BaseSource` mapping has not been specified. Since no mapping has been specified, the code will try to AutoMap to the destination and will fail since the column doesn't exist.

Let me know if that explains correctly the issue.

Best Regards,

Jonathan
