### ISSUE TITLE
Interbase bulkinsert produces error

### ISSUE THREAD

**Issue by GirusVirus** [zzzprojects/Dapper-Plus#100]
Hi, I am trying to use dapper-plus and getting the following error "The Provider could not be resolved. You must explicitly set the Provider." it is very simple insert operation. I understand that Firebird and Interbase are not officially supported, is there a way that I can supply the "provider", or am I out of luck.

`void BulkUpload(List<PartListModel> data, string connectionString, string tableName)
{

	DapperPlusManager.Entity<PartListModel>().Table("tableName");
		

	using (IDbConnection conn = new IBConnection(connectionString))
	{
		conn.BulkInsert(data);
	}
}
`

Please help.

Best,

**Comment by JonathanMagnan** [comment]
Hello @GirusVirus ,

Long time we didn't get a `Firebird` request.

We will look at it.

If I remember correctly, we are supporting it for our `Entity Framework Extensions` library but I'm not sure why we never added it on our `Dapper Plus` library.

I will give you more info soon.

Best Regards,

Jon

**Comment by GirusVirus** [comment]
tank you Jon,

I am using this ADO.Net Driver  
Embarcadero /IB.NETDataProvider  just released in May 21.

Thanks,

**Comment by JonathanMagnan** [comment]
Hello @GirusVirus ,

Unfortunately, we only support the following provider: https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient/

In your case, even if you explicitly set it, that will not be supported.

We currently don't plan to add any more providers so I guess you are "out of luck" :(

Probably not the answer you wanted but let me know if that answer at least to it correclty.

Best Regards,

Jon

**Comment by GirusVirus** [comment]
Hi Jon,
Thank you for responding so quickly, yes, that is not what I was hoping for, I understand. I was just hoping that Firebird and Interbase are so much alike, that it would not be an issue or much diffrent. Thanks. Maybe if more demand comes up, you can reconsider. 

Best,

**Comment by JonathanMagnan** [comment]
We never know but at this moment, time is missing so this kind of development is just impossible ;(
