### ISSUE TITLE
Add Like Dapper TypeHandler

### ISSUE THREAD

**Issue by znyet** [zzzprojects/Dapper-Plus#107]
hello! dapper can add TypeHandler like
```csharp
public class MyTypeHandler<T> : SqlMapper.TypeHandler<T>
{
        public override T Parse(object value)
        {
            return JsonConvert.DeserializeObject<T>((string)value);  // Newtonsoft.Json
        }

        public override void SetValue(IDbDataParameter parameter, T value)
        {
            parameter.Value = (value == null) ? DBNull.Value : JsonConvert.SerializeObject(value);
            parameter.DbType = DbType.String;
        }
 }
```
```csharp
public class Student
{
	public int Id { get; set; }

	public string Name { get; set; }

	[Column(0, "", "varchar(8000)")]
	public Child cc { get; set; } //is an varchar column in database
}

public class Child
{
	public string Name { get; set; }

	public int Sex { get; set; }
}

//map it 
SqlMapper.AddTypeHandler(new MyTypeHandler<Child>());

```
can dapper plus add like this?

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

Thank you for reporting, we already discussed it recently.

At this moment, we currently have too many requests but we will look at it at the beginning of March.

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Thank for the additional information ;)

**Comment by znyet** [comment]
Hello @JonathanMagnan ,
when z.dapper.plus impl TypeHandler.  
I think z.dapper.plus can add an global TypeHandler for all Not added class, such as

```csharp
//it default is null
public static TypeHandler GlobalTypeHandler = null;

//we can config it,if we no hand add TypeHandler,it will use default it (other hand add,use hand add)
GlobalTypeHandler = new JsonTypeHandler();

```
Because if in project,we has 100 or 1000 or List<T> and more.
we must add so much TypeHandler.

Best regards,
znyet

**Comment by znyet** [comment]
Hello @JonathanMagnan ,
when z.dapper.plus impl TypeHandler, we hand add TypeHandler, and use it first. 
I think z.dapper.plus can add an GlobalTypeHandler, when not found hand TypeHandler will use it default.
such as
```csharp
//default is null
public static ITypeHandler GlobalTypeHandler = null;

//use json as default
GlobalTypeHandler  = new JsonTypeHandler();
```
because in project, if has 100 or 1000 class or List and more.
we must add so much TypeHandler, and some times forget config it.
use GlobalTypeHandler will helpfull.

Best regards,

znyet

**Comment by znyet** [comment]
Hello @JonathanMagnan ,
How many days will it take to complete ITypeHandler.
I think this function is still very practical.
Thank you for your hard work.

Best regards,

znyet

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

I cannot give you an estimated date yet but we started to investigate this request this week.

At this moment, this is going really well as we success quickly to implement the "SetValue" part for some datasource but there is still some work to do. The parse should be really easy as well.

What might be hard would be to make sure and test all data sources we support.

I will be able to give you a better ETA next week.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

Just to let you know, we hope to complete our test probably next week on that feature.

We currently target the date April 5 to release it if there is no problem

Best Regards,

Jon

**Comment by znyet** [comment]
Thank you for your hard work.
I'm looking forward to it.

**Comment by znyet** [comment]
Hello @JonathanMagnan ,

Will release ITypeHandler tomorrow?

Best regards,

znyet

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

Unfortunately, we didn't release anything this week.

However, this is in our merge list for next week. So this is coming really soon.

Best Regards,

Jon

**Comment by znyet** [comment]
Hello Jon, 
i test it success, good job!
thank you for your hard work.

```csharp
internal class JsonNetTypeHandler : IBulkValueConverter
    {
        public object ConvertFromProvider(Type destinationType, object value)
        {
            if (value == null || value == DBNull.Value)
            {
                return default;
            }
            try
            {
                var val = (string)value;
                if (val == "")
                {
                    return default;
                }
                return JsonConvert.DeserializeObject(val, destinationType);
            }
            catch
            {
                return default;
            }
        }

        public object ConvertToProvider(object value)
        {
            if (value == null)
            {
                return DBNull.Value;
            }
            return JsonConvert.SerializeObject(value);
        }
```
```csharp
DapperPlusManager.AddValueConverter(typeof(T), new JsonNetTypeHandlerZ());
```
Best Regards,

znyet

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

You have been faster than me ;)

The v4.0.27 has been released yesterday.

I guess I don't need to show you an example as you perfectly used it. You can either use the `IBulkValueConverter` or `BulkValueConverter<T>`.

Best Regards,

Jon
