### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by svhero658** [zzzprojects/Dapper-Plus#11]
Calling different DapperPlusManager.ValidateLicense overloads have different behavior. I think this is a bug, please fix.

**Comment by JonathanMagnan** [comment]
Hello @svhero658 ,

What do you mean by different behavior?

We have two overloads:

```csharp
public static bool ValidateLicense(DapperProviderType provider = DapperProviderType.SqlServer)
public static bool ValidateLicense(out string errorMessage, DapperProviderType provider = DapperProviderType.SqlServer)
```

Best Regards,

Jonathan

**Comment by svhero658** [comment]
The overload without out parameter cannot verify the license correctly

**Comment by JonathanMagnan** [comment]
You are right. We made a mistake by copying some code from one of our other libraries.

The v1.2.8 has been released:
https://www.nuget.org/packages/Z.Dapper.Plus/

Let me know if everything now works as expected.

Best Regards,

Jonathan

**Comment by svhero658** [comment]
OK I'll check later. Thanks for your timely response.

**Comment by JonathanMagnan** [comment]
Hello @svhero658 ,

I will close this issue since it should be solved.

Best Regards,

Jonathan
