### ISSUE TITLE
Allow passing IConfiguration to ValidateLicense, OR add new AddSingleLicense() call?

### ISSUE THREAD

**Issue by VictorioBerra** [zzzprojects/Dapper-Plus#112]
ValidateLicense appears to only check appsettings.json, why can't I provide a built IConfiguration to it instead?

I tried to AddLicense before ValidateLicense and it still errored (because I have placeholders that get transformed in my appsettings.json), so an alternative approach could be to NOT check appsettings if someone called AddLicense manually?

IE add a method called `AddSingleLicense()` which would be the ONLY license ValidateLicense would look for.

My license can come from:

- args
- environment variables
- secrets.json
- appsettings.[Environment].json
- Azure KeyVault Configuration Provider

None of which are supported by ValidateLicense today.

**Comment by VictorioBerra** [comment]
This is my workaround for now, you must remove `"Z.EntityFramework.Extensions": {...}` from appsettings.json :

```csharp
var config = serviceProviderFromScope.GetRequiredService<IConfiguration>();

var zDapperPlusLicense = config.GetSection("Z.EntityFramework.Extensions.DapperPlusLicense");

DapperPlusManager.AddLicense(
    zDapperPlusLicense.GetValue<string>("LicenseName"),
    zDapperPlusLicense.GetValue<string>("LicenseKey"));

var dapperLicenseValidationResult = DapperPlusManager.ValidateLicense(out var errorMessage);

if (!string.IsNullOrEmpty(errorMessage))
{
    logger.LogError("Error validating DapperPlus license {Error}", errorMessage);
}
else
{
    logger.LogInformation("DapperPlus license validation result {DapperLicenseValidationResult}", dapperLicenseValidationResult);
}
```

## Ideally, it would look like this:

```csharp
var config = serviceProviderFromScope.GetRequiredService<IConfiguration>();
var dapperLicenseValidationResult = DapperPlusManager.ValidateLicense(config , out var errorMessage);
```

or:

```csharp
var config = serviceProviderFromScope.GetRequiredService<IConfiguration>();

// Note this is the section it looks for interally today
var zDapperPlusLicense = config.GetSection("Z.EntityFramework.Extensions");

DapperPlusManager.AddSingleLicense(
    zDapperPlusLicense.GetValue<string>("LicenseName"),
    zDapperPlusLicense.GetValue<string>("LicenseKey"));

// This will now ignore the internal check for appsettings.json
var dapperLicenseValidationResult = DapperPlusManager.ValidateLicense(out var errorMessage);
```

**Comment by JonathanMagnan** [comment]
Hello @VictorioBerra ,

Thank you for reporting.

I will assign this to my developer to discuss if we should improve this part or not of our code.

Best Regards,

Jon

**Comment by VictorioBerra** [comment]
Makes sense, thanks for discussing!
