### ISSUE TITLE
Allow DapperPlusContext to support transactions

### ISSUE THREAD

**Issue by VictorioBerra** [zzzprojects/Dapper-Plus#114]
### Description
From the docs here: https://dapper-plus.net/getting-started-mapping#instance-context-mapping

How can we support the following situation?

```csharp
using var connection = new SqlConnection(connectionString);
await connection.OpenAsync(cancellationToken);
using var transaction = await connection.BeginTransactionAsync(cancellationToken);

var context = new DapperPlusContext(transaction); // <---------- `transaction`!
```

**Comment by VictorioBerra** [comment]
Okay so apparently it supports it as a second argument: `new DapperPlusContext(connection, transaction)`

So two questions now:

1. Do I need to call `connection.OpenAsync`? Why does it need connection AND my transaction?
2. How do I call `.Commit()` on my transaction? `context.Commit()` is not a method. Do I call `transaction.Commit()` outside of context?

**Comment by JonathanMagnan** [comment]
Hello @VictorioBerra ,

> Do I need to call connection.OpenAsync

Yes, you need to `Open` the connection. This is not required by our library but is required to begin a transaction.

Without a transaction, you would not have to `Open` it.

> Why does it need connection AND my transaction?

That's a good question. Honestly, I'm not sure exactly remember the initial reason why we force to pass the connection. I know some special providers could require both (when the connection is overridden but the transaction holds the underlying connection).

> How do I call .Commit() on my transaction? context.Commit() is not a method. Do I call transaction.Commit() outside of context?

You call `transaction.Commit()`

Let me know if that answer all your question.

Best Regards,

Jon
