### ISSUE TITLE
Issue with Bulk update with Timestamp column

### ISSUE THREAD

**Issue by shobhitkasliwal** [zzzprojects/Dapper-Plus#12]
Hi 
I am facing an issue where my model has a timestamp column and bulk update is trying to update that column which sql does not allow. 
is there any way I can ignore all timestamp columns from bulk update ?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @shobhitkasliwal ,

You can use the `Ignore` mapping options in your mapping.

## Dapper Plus - Mapper - Ignore
Sets column(s) to ignore.

### Example
Ignore single column
```csharp
DapperPlusManager.Entity<Order>()
                 .Ignore(x => x.Column1);
```

Ignore many columns
```csharp

DapperPlusManager.Entity<Order>()
                 .Ignore(x => new { x.Column1, x.Column2, x.Column3 });
```

Let me know if that successfully answer to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Please reopen if you have more question

Best Regards,

Jonathan
