### ISSUE TITLE
Set ColumnSynchronizeDeleteKeySubsetExpression without .Entity<Whatever>()?

### ISSUE THREAD

**Issue by VictorioBerra** [zzzprojects/Dapper-Plus#124]
### Description
Can we have a feature to pass a string for the column name for `ColumnSynchronizeDeleteKeySubsetExpression`?

I have code like this:

```csharp
            context
                .Entity<DatabasePersonWorkersContactAddresses>()
                .Table("Person_Workers_Contact_Addresses")
                .Identity(x => x.Id)
                .Map(x => x.WorkerId, "Worker_Id")
                .AutoMap()
                .UseBulkOptions(options =>
                {
                    options.BatchSize = this.workDayStorePersonWorkersServiceOptions.DapperPlusBulkOperationBatchSize;
                    options.BatchTimeout = this.workDayStorePersonWorkersServiceOptions.DapperPlusBulkOperationBatchTimeout;
                    options.RetryCount = this.workDayStorePersonWorkersServiceOptions.DapperPlusBulkOperationRetryCount;

                    // Dont delete unless IsFutureEffectiveDate = 0
                    options.ColumnSynchronizeDeleteKeySubsetExpression = c => c.IsFutureEffectiveDate;

                    // Dont update unless IsFutureEffectiveDate = 0
                    options.MergeMatchedAndConditionExpression = c => c.IsFutureEffectiveDate;

                    options.Log = Log;
                })
                .MapValue(maybeSyncTimestamp, nameof(DatabasePersonWorkersContactAddresses.BulkSyncDate));

            context
                .Entity<DatabasePersonWorkersName>()
                .Table("Person_Workers_Name")
                .Identity(x => x.Id)
                .Map(x => x.WorkerId, "Worker_Id")
                .AutoMap()
                .UseBulkOptions(options =>
                {
                    options.BatchSize = this.workDayStorePersonWorkersServiceOptions.DapperPlusBulkOperationBatchSize;
                    options.BatchTimeout = this.workDayStorePersonWorkersServiceOptions.DapperPlusBulkOperationBatchTimeout;
                    options.RetryCount = this.workDayStorePersonWorkersServiceOptions.DapperPlusBulkOperationRetryCount;

                    options.Log = Log;

                    // Dont delete unless IsFutureEffectiveDate = 1
                    options.ColumnSynchronizeDeleteKeySubsetExpression = c => c.IsFutureEffectiveDate;

                    // Dont update unless IsFutureEffectiveDate = 1
                    options.SynchronizeMatchedAndConditionExpression = c => c.IsFutureEffectiveDate;
                })
                .MapValue(maybeSyncTimestamp, nameof(DatabasePersonWorkersName.BulkSyncDate));

                await context
                    .BulkActionAsync(
                        x => x.BulkMerge(personWorkerEntities)
                            .Include(x =>
                                x.ThenBulkMerge(y => y.DatabasePersonWorkersName)),
                        cancellationToken);
```

[Based on our previous thread](https://github.com/zzzprojects/Dapper-Plus/issues/115) UseBulkOptions wont work like that because it needs to be chained to the `BulkActionAsync`. But you can see my UseBulkOptions repeats. I would like to just set it a single time. Is this possible?

Also looks like I cannot apply `UseBulkOptions()` to `ThenBulkMerge()`? What is the best way to accomplish what I am trying to do above?

### Further technical details
- Dapper version: 2.0.123
- Dapper Plus version: 5
- Database Provider: MSSQL

**Comment by JonathanMagnan** [comment]
Hello @VictorioBerra 

> Can we have a feature to pass a string for the column name for ColumnSynchronizeDeleteKeySubsetExpression?

It should already be supported through the option `ColumnSynchronizeDeleteKeySubsetNames`, which allows you to pass a list of strings representing all the column names you want to use.

> Also looks like I cannot apply UseBulkOptions() to ThenBulkMerge()? What is the best way to accomplish what I am trying to do above?

The `connection.UseBulkOptions` should be only for configurations like `BatchSize` that you don't mind applying to every bulk operation that chain after.

We usually recommend putting all custom options directly in the mapping and using a mapping key instead: https://dapper-plus.net/getting-started-mapping#mapper-key , which allows you to map an entity type in multiple different ways.

Let me know if you need more help with any of your two questions.

Best Regards,

Jon

**Comment by VictorioBerra** [comment]
Okay that answers my questions. `UseBulkOptions()` will apply to every chained Bulk operation.

I will switch to mapping keys since that seems less "global" and my mappings can apply directly to bulk operations.

Just some extra clarification, `ColumnSynchronizeDeleteKeySubsetNames` can only be applied via `UseBulkOptions` and cannot be set in mapping and used with mapping keys right? It applies to the entire bulk operation across all entities?

**Comment by JonathanMagnan** [comment]
Hello @VictorioBerra ,

When you use a syntax similar to this:

```csharp
context.Entity<IEntityType>("mappingkey")
	.UseBulkOptions(options =>
	{
	});
```

The `UseBulkOptions` will only apply to this specific entity type whenever this key is used. It will not affect any other bulk operations but only those that use this exact mapping key.

Any configuration, in fact, should only apply only whenever you use this `mappingkey` and doesn't affect any other chained methods.

---

However, if you use the `UseBulkOperations` in the context such as:

```csharp
context.UseBulkOptions(options => {}).BulkInsert
```

it will apply to all bulk operations that will be chained.

Let me know if that's more clear.

Best Regards,

Jon

**Comment by VictorioBerra** [comment]
Makes sense to me. Thanks!
