### ISSUE TITLE
Set schema name

### ISSUE THREAD

**Issue by deextercz** [zzzprojects/Dapper-Plus#13]
Lets say that I have this configuration:
```
DapperPlusManager.Entity<StationEntity>()
    .Table("Station");
```
In DB I have [raw].[Station] how to solve this to insert items like this

```
connection.BulkInsert(items); 
```
to different schema then dbo?

**Comment by JonathanMagnan** [comment]
Hello @deextercz ,

You can append the schema name to the table name

```csharp
DapperPlusManager.Entity<StationEntity>()
    .Table("raw.Station");
```

Let me know if that answer to your question correctly

Best Regards,

Jonathan

**Comment by deextercz** [comment]
Thanks it looks like that it works
