### ISSUE TITLE
Feature Request - suppress update if nothing changed.

### ISSUE THREAD

**Issue by geremysremitter** [zzzprojects/Dapper-Plus#130]
### Description
When importing hundreds of thousands of records and this is especially true of BulkMerge - is it possible to include a merge option that skips running an update on a record if nothing has changed ? 

### Exception
None - this is a feature request

### Fiddle or Project (Optional)

would like to perform something to the effect of 

`DapperPlusManager.Entity<Contact>().UseBulkOptions(o => { o.IsSkipUpdateIfNoChanges; });`

Even better would be to allow a list of 'Ignore' fields.  So for example if First and Last name of a contact are unchanged, but say 'IsActive' is something we wish to ever touch during insert, we can omit this (or more) fields from triggering an update.

### Further technical details
Dapper version: 2.0.123
Dapper Plus version: 6.0.0
Dapper Contrib: 2.0.78
Database Provider: SQL Server (Azure)

**Comment by JonathanMagnan** [comment]
Hello @geremysremitter ,

Sure, here is the documentation from EF Extensions (it works the same in Dapper Plus): https://entityframework-extensions.net/matched-and-one-not-condition

You either choose which columns you want to check or which columns you want to skip. The `UPDATE` statement will be made only if at least one value is different.

Here is a Fiddle that show how to use it: https://dotnetfiddle.net/FCe1bO

Let me know if you need more help with this request.

Best Regards,

Jon

**Comment by geremysremitter** [comment]
Ok wow.  Thanks Jon, I was able to get this to do exactly what we were looking for.  Very nice and thanks again !
