### ISSUE TITLE
Support for Sybase for Bulk Insert

### ISSUE THREAD

**Issue by diegotravieso** [zzzprojects/Dapper-Plus#132]
### Description
I am using a .Net application that connects to a sybase database and wanted to see if the bulk insert functionality was possible.

### Exception
I'm currently getting the following error: The Provider could not be resolved. You must explicitly set the Provider.

I read the supported DBs and I don't see sybase in it. I just wanted to confirm if there is no support for it or if the error I'm having is due to something else that I could fix.

Thanks!

**Comment by JonathanMagnan** [comment]
Hello @diegotravieso ,

Unfortunately, `sysbase` is not supported.

There is currently no short-term plan to support additional providers.

Best Regards,

Jon
