### ISSUE TITLE
bulk insert very slow on mariadb version≥10.6.0

### ISSUE THREAD

**Issue by znyet** [zzzprojects/Dapper-Plus#139]
dear！

```
class People
{
      public long Id { get; set; }
      public string Name { get; set; }
      public string Address { get; set; }
}
```

when i use MySqlConnector， mariadb version≥10.6.0   bulk insert  1 million record is very slow.
but in mariadb version 10.4 is very fast.
why?

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

Could you let us know what kind of performance difference you had? How long does it take in both versions?

Are you using the **same exact project** and only changing the connection string?

Best Regards,

Jon
