### ISSUE TITLE
Whether support multiple primary keys?

### ISSUE THREAD

**Issue by winsonet** [zzzprojects/Dapper-Plus#14]
How about there are multiple primary keys in a model? it also can handle? 

thanks!

**Comment by JonathanMagnan** [comment]
Hello @winsonet ,

Sure, the library can easily handle this. 

The `MappingKey` let you specify multiple mapping for the same entity.

```csharp
// Default
DapperPlusManager.Entity<Order>()
                 .Key(order => order.OrderID);
				 
// CustomKey1	 
DapperPlusManager.Entity<Order>("CustomKey1")
                 .Key(order => new { order.CustomerID, order.Number });
				 
				 
conn.BulkInsert(list);
conn.BulkInsert("CustomKey1", list);
```

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by winsonet** [comment]
oh, that's great, i will try it, thanks!!
