### ISSUE TITLE
When Connecting to Snowflake System.Exception: 'The Provider could not be resolved. You must explicitly set the Provider.'

### ISSUE THREAD

**Issue by jammer123b** [zzzprojects/Dapper-Plus#144]
### Description
When I try to use a snowflake connection.
I'm doing something like:
using IdbConnection connection = new SnowflakeDbConnection(connString);

I Get the connection but when I try to do the connectin.BulkInsert(data);
I get the following Error:
System.Exception: 'The Provider could not be resolved. You must explicitly set the Provider.'

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
The value of what is in the details is:
Name: $exception
Value: Internal error in the expression evaluator
```
Exception message:
Stack trace:
```

### Fiddle or Project (Optional)
If you are able, 

Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/kV5RHX

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.
/***********************My Code**********************************************
This is a console app.
You will need to add the following NuGet Packages:
<PackageReference Include="Dapper" Version="2.1.35" />
<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
<PackageReference Include="Snowflake.Data" Version="4.0.0" />
<PackageReference Include="Z.Dapper.Plus" Version="7.5.0" />

I was able to use Sql and MySql with no issues.  I have excluded those packages from the list
My Method is this:
public async Task BulkInsert<T>(IEnumerable<T> data, string tableName, string connectionStringName = "DefaultSnow") where T : class
{
    var _config  = new ConfigurationBuilder()
                                                         .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                                                         .Build(); 
    string? connectionString = _config.GetConnectionString(connectionStringName);

    using IDbConnection connection = new SnowflakeDbConnection(connectionString);
    DapperPlusManager.Entity<T>()
        .Table(tableName);
    
    await connection.BulkInsertAsync(data);

}

I'm calling it like this:
await BulkInsert(codeRepos, "DDAR_APPS.DEVSANDBOX.code_repo_source", "DefaultSnow");

you will need a snowflake connection.  I can't provide that for security reasons.
/************************************************************************************************/
_Note: More information you provide, faster we can implement a solution._

### Further technical details
- Dapper version: [Dapper v2.1.15]
- Dapper Plus version: [Dapper Plus v6.0.5]
- Database Server version: [SQL Server 2002]
- Database Provider version (NuGet): [Microsoft.Data.SqlClient v5.1.2]

**Comment by JonathanMagnan** [comment]
Hello @jammer123b ,

Unfortunately, `Snowflake` is not one of our supported providers for Dapper Plus.

We currently support:
- SQL Server
- Oracle
- MySQL
- PostgreSQL
- SQLite
- SQL Compact

There is currently no short-term plan to add more providers.

Let me know if that answers your problem correctly, even if it's not a positive answer.

Best Regards,

Jon
