### ISSUE TITLE
MSSQL Duplicate Key Violations on Bulk Merge even when Key is mapped

### ISSUE THREAD

**Issue by andrewbutlerboudakiankce** [zzzprojects/Dapper-Plus#146]
### Description
I am not sure if I am utilizing the manager wrong for mapping tables or if this is an issue with Dapper Plus, but I have a table mapped through DapperPlusManager with a Key selector being specified and am still running into duplicate key errors when attempting to run `transaction.BulkMerge<T>(...)` on an `IEnumerable<T>`. I am manually de-duping the `IEnumerable<T>` with LINQ Group By using the exact same key selector as is being mapped through the manager, so the issue is not the enumerable itself being passed in.

Please let me know if there is some option I am missing or if this is a known bug.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception thrown: "Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Table'. Cannot insert duplicate key in object 'Schema.Table'. The duplicate key value is (Value1, Value2, Value3, Value4).
The statement has been terminated.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at .(DbCommand , BulkOperation , Int32 )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
   at Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(DapperPlusContext context, IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkMerge[T](IDbTransaction transaction, String mapperKey, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkMerge[T](IDbTransaction transaction, IEnumerable`1 items, Func`2[] selectors)
   at DatabaseSinkLoader.Load[T,S](PerformContext context, IDbTransaction transaction, IEnumerable`1 fullPipelineDataSets) in D:\PathToInternalLibrary\InternalLibrary.cs:line 14
   at Transformer.TransformAndLoad() in D:\PathToFile\File.cs:line 206
ClientConnectionId:connectionId
Error Number:2627,State:1,Class:14" in transformer.
```

### Fiddle or Project (Optional)
Here is all the relevant code with unnecessary internal naming made generic:
- Manager Mapping
```
public interface IDapperModel<T>
{
    public abstract static Expression<Func<T, object>> GetKey();
}
public class Models
{
    public static void ConfigureDapperPlus()
    {
        MapTable<Table>
    }

    public static string GetTableName<T>()
    {
        TableAttribute? tableAttribute = typeof(T).GetCustomAttributes(false).OfType<TableAttribute>().FirstOrDefault();
        return tableAttribute == null ? "Unknown Table" : tableAttribute.Name;
    }

    private static void MapTable<T>() where T : class, IDapperModel<T>
    {
        DapperPlusManager.Entity<T>()
            .Table(GetTableName<T>())
            .Key(T.GetKey());
    }
}
```

- Table Definition
```
[Table("Schema.Table")]
public class Table : IDapperModel<Table>
{
    [ExplicitKey]
    public int Column1 { get; set; }
    [ExplicitKey]
    public int Column2 { get; set; }
    [ExplicitKey]
    public DateTimeOffset Column3 { get; set; }
    [ExplicitKey]
    public DateTimeOffset Column4 { get; set; }
    public int Column5 { get; set; }
    public bool Column6 { get; set; }
    public double Column7 { get; set; }

    public static Expression<Func<Table, object>> GetKey() => row => new { row.Column1, row.Column2, row.Column3, row.Column4 };
}
```

- Usage
```
public static class DatabaseSinkLoader
{
    public static void Load<T, S>(PerformContext? context, IDbTransaction transaction, IEnumerable<FullPipelineDataSet<T, S>> fullPipelineDataSets) where T : ISourceDataSet where S : IDapperModel<S>
    {
        context?.WriteLine("Flattening transformed datasets");
        IEnumerable<S> flattenedDataSets = fullPipelineDataSets.Where(x => x.TransformedDataSet.Data != null)
            .SelectMany(x => x.TransformedDataSet.Data!)
            .GroupBy(S.GetKey().Compile())
            .Select(group => group.First());

        context?.WriteLine("Loading DataSets");
        transaction.BulkMerge(flattenedDataSets); // This line here is causing the exception
        ...
        // Code beyond here irrelevant to issue
    }
}
```

### Further technical details
- Dapper version: [Dapper v2.1.15]
- Dapper Plus version: [Dapper Plus v6.0.5]
- Database Server version: [SQL Server 2019]
- Database Provider version (NuGet): [Microsoft.Data.SqlClient v5.1.2]

**Comment by JonathanMagnan** [comment]
Hello @andrewbutlerboudakiankce ,

Can you share your table creation SQL script? That's one important part missing from your initial message, as potentially, there is an issue when comparing versus when saving the `DateTimeOffset` properties in your database.

Best Regards,

Jon

**Comment by andrewbutlerboudakiankce** [comment]
Here's the base table definition and indexes
```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Schema].[Table](
	[Column1] [smallint] NOT NULL,
	[Column2] [int] NOT NULL,
	[Column3] [datetimeoffset](0) NOT NULL,
	[Column4] [datetimeoffset](0) NOT NULL,
	[Column5] [smallint] NOT NULL,
	[Column6] [bit] NOT NULL,
	[Column7] [float] NOT NULL,
 CONSTRAINT [PK_Table] PRIMARY KEY CLUSTERED 
(
	[Column1] ASC,
	[Column2] ASC,
	[Column3] ASC,
	[Column4] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Schema].[Table] ADD  DEFAULT ('1900-01-01 00:00:00 +00:00') FOR [Column3]
GO

ALTER TABLE [Schema].[Table]  WITH CHECK ADD  CONSTRAINT [FK_Table_Column1] FOREIGN KEY([Column1])
REFERENCES [Column1Schema].[Column1Table] ([Column1Id])
GO

ALTER TABLE [Schema].[Table] CHECK CONSTRAINT [FK_Table_Column1]
GO

ALTER TABLE [Schema].[Table]  WITH CHECK ADD  CONSTRAINT [FK_Table_Column2] FOREIGN KEY([Column2])
REFERENCES [Column2Schema].[Column2Table] ([Column2Id])
GO

ALTER TABLE [Schema].[Table] CHECK CONSTRAINT [FK_Table_Column2]
GO

CREATE NONCLUSTERED INDEX [NCI_Table_Column2] ON [Schema].[Table]
(
	[Column2] ASC
)
INCLUDE([Column5],[Column6],[Column7]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
```

**Comment by JonathanMagnan** [comment]
Thank you for this additional information,

We will look at it today.

Best Regards,

Jon

**Comment by andrewbutlerboudakiankce** [comment]
Hi Jon,

Did you determine the cause of the issue?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @andrewbutlerboudakiankce ,

I asked for an update from my developer, to which the issue was assigned; he should give me one later during the day.

The hypothesis is that there is probably some issue with some truncation and comparisons with the `[datetimeoffset](0)` column.

You could already probably confirm it by merging 1 row versus 20 rows (a different strategy is applied over 10 rows). We expect the 1 row will have the issue but not the 20 rows, as the `datetimeoffset` column value will already be truncated into the temporary table.

I should get this confirmation very soon, or perhaps another reason why this issue happens.

Best Regards,

Jon

**Comment by andrewbutlerboudakiankce** [comment]
Hi Jon, thanks for confirming this, as a stopgap for the time being if this is the issue I'm going to add a setter truncating sub-second values and see if that resolves the issue on my end, thanks.

**Comment by JonathanMagnan** [comment]
Hello @andrewbutlerboudakiankce ,

My developer provided me with a lot more information.

It looks like that's not a bug within our library but somewhat more a bug within how the `SqlParameter` work.

Read the following remark in the yellow section: [Sql Parameter with Scale 0](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlparameter.scale?view=netframework-4.8.1#remarks)

You will find the following text:

> There is currently no way to send a parameter as datetime2(0). Scales 1-7 work as expected. This problem applies to DateTimeOffset and Time as well.

So when you save 10 rows or less, your `Column3`, by example, will compare a DateTimeOffset(7) with the DateTimeOffset(0) in the database. It will lead to the row having a different value (which means the row doesn't exist), but when inserting, the DateTimeOffset(7) will be truncated to a DateTimeOffset(0), leading to the Duplicate Key Violations error.

This error currently doesn't happen when there are more than 10 rows because we bulk insert in a temporary table that have already the column as a DateTimeOffset(0).

You can fix this issue within our library by forcing a temporary table such as:

```csharp
context.BulkSaveChanges(options =>
{
   options.TemporaryTableMinRecord = 0;
});
```

However, I recommend you reconsider using a `[datetimeoffset](0)` if possible. As you understand, it will always lead to some weird error like this one.

---

Indeed, truncating the value as you proposed will work (we didn't try it but it makes sense).

Let us know if you need more help with this issue.

Best Regards,

Jon

**Comment by andrewbutlerboudakiankce** [comment]
Hi Jon,

Thank you for the information, I have successfully implemented and tested the stopgap solution mentioned earlier to truncate values which has appeared to have resolved the issue. Will close this since it's not an issue with Dapper Plus specifically.
