### ISSUE TITLE
Monthly Trial Release - October

### ISSUE THREAD

**Issue by AliRezaBoroujerdian** [zzzprojects/Dapper-Plus#147]

**Comment by AbanobMagdy90** [comment]
Where the Monthly Trial Release for October

**Comment by JonathanMagnan** [comment]
Hello, 

Sorry for the inconvenience, we are currently working on releasing a new trial and it will be available shortly. 

The trial expires at the end of each month. We do not recommend using the trial in a production machine or client machine; Occasionally, there may be a few days lapse between releases. 

That said, we highly suggest that companies purchase a license so they won’t have to update their production environment every month. 

Don't hesitate to contact us for further information regarding our product. 

Jon

**Comment by AbanobMagdy90** [comment]
Dears
You are right but the cost of the license is above my ability

**Comment by JonathanMagnan** [comment]
Hello @AbanobMagdy90 ,

The new version of Dapper Plus is now available.

Best Regards,

Jon
