### ISSUE TITLE
Calling PostGis Functions

### ISSUE THREAD

**Issue by cdbridger-tracplus** [zzzprojects/Dapper-Plus#148]
I have a dapper method that I'm trying to replace with bulk insert but I'm unsure how to go about it.

here is the current dapper method
```
 const string sql = @"
INSERT INTO markers.markers (organisation_id, name, type, geom, icon, colour)
VALUES (@OrganisationId, @Name, @Type, ST_SetSRID(ST_MakePoint(@Lon, @Lat, @Alt), 4326), @Icon, @Colour);
";

        await this.database.Execute(sql, new
        {
            marker.OrganisationId,
            marker.Name,
            Type = marker.Type.ToString(),
            Lat = marker.Position.Coordinates.Latitude,
            Lon = marker.Position.Coordinates.Longitude,
            Alt = marker.Position.Coordinates.Altitude ?? 0D,
            marker.Icon,
            marker.Colour,
        });
```

as you can see the column `geom` currently takes `ST_SetSRID(ST_MakePoint(@Lon, @Lat, @Alt), 4326)`

which I'm unsure how to emulate/execute/map to using dapper plus.

Any help would be much appreciated.

EDIT: Here is my model that I have annotated to be used with dapper plus.

```
[Table("markers", Schema = "markers")]
public class Marker
{
    [Key]
    public long Id { get; set; }
    [Column("organisation_id")]
    public string OrganisationId { get; set; } = string.Empty;
    [Column("name")]
    public string Name { get; set; } = string.Empty;
    [Column("type")]
    public MarkerType Type { get; set; } = MarkerType.POI;
    [Column("icon")]
    public string Icon { get; set; } = string.Empty;
    [Column("colour")]
    public string Colour { get; set; } = string.Empty;
    [NotMapped]
    public Point Position { get; set; } = new(new Position(0, 0));
}
```

and I tried toying around with adding this but couldn't get it to work (as I couldn't access the value in the options)

```
DapperPlusManager.Entity<Marker>().MapWithOptions(x => x.Position, options =>
{
    options.DestinationName = "geom";
    options.FormulaInsert = "ST_SetSRID(ST_MakePoint(@Latitude, @Longitude), 4326)";
});
```

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

Thank you for reporting.

I don't think it's possible to support your scenario, but we are very close to having everything for it. I created a quick prototype, and I was able to make it work.

I will look at it with my developer and see what can be done.

Best Regards,

Jon

**Comment by cdbridger-tracplus** [comment]
Thank you very much! What sort of time line would you be looking at to make the required changes? (days, weeks, months). Just so I know if I need to find an alternative solution in the meantime!

Cheers

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

I'm currently traveling until mid-November, so all releases are currently paused for 2 or 3 weeks.

Could you let me know the type of the @Latitude and @Longitude? I don't think we will be able to support types with precision, such as decimals, but we could try to support type like `int` correctly.

Best Regards,

Jon

**Comment by cdbridger-tracplus** [comment]
Ah, it's from GeoJSON.Text.Geometry , they are all doubles.

```
namespace GeoJSON.Text.Geometry
....
public Position(double latitude, double longitude, double? altitude = null)
```

**Comment by JonathanMagnan** [comment]
Is there a reason you do not map the final value that should be saved instead of calling a method in your database? There is usually some way to get the value to save directly through your application instead of your database

You can map a value "factory" like shown in this example: https://dapper-plus.net/getting-started#mapping-and-mapping-key

```csharp
.Map(x => x.Items.Sum(y => y.Price), "TotalAmount")
```

Best regards,

Jon

**Comment by cdbridger-tracplus** [comment]
I would then have to figure out how to reimplement the PostGis Postgres extension functionality in c# land for ST_SetSRID() and ST_MakePoint() which is a route we are very unlikely to take here. 

Just to show you what a row looks like in the database:
```
technical,Seagull Hill,POI,01010000A0E6100000689C2BD5F53F65409D0E0987DE7D46C00000000000000000,generic,#f44336
```

where
```
01010000A0E6100000689C2BD5F53F65409D0E0987DE7D46C00000000000000000
```

is the output of the two methods being called on the latitude, longitude and altitude being passed in. 

https://postgis.net/docs/ST_MakePoint.html

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

People usually use the [NetTopologySuite](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Point.html) for this. It should contains everything you need but I'm not an expert in this, so I cannot really help you more.

Best Regards,

Jon
