### ISSUE TITLE
Typo on Homepage

### ISSUE THREAD

**Issue by digentltd** [zzzprojects/Dapper-Plus#20]
There is a typo as highlighted in the screenshot of Dapper-Plus on the homepage http://dapper-plus.net/ as in my screen shot below.

![image](https://user-images.githubusercontent.com/16516455/34084786-35da0e3c-e37e-11e7-9d93-2b00a69874d6.png)

Also the same issue on http://dapper-plus.net/overview  as in screen shot.

![image](https://user-images.githubusercontent.com/16516455/34084870-58acb3e6-e37f-11e7-9675-754cf84e472e.png)

**Comment by JonathanMagnan** [comment]
Thank a lot @digentltd  for reporting.

The issue has been fixed everything. It was also in the readme.

Best Regards,

Jonathan
