### ISSUE TITLE
1.3.6 bulk insert failing? 

### ISSUE THREAD

**Issue by calemith** [zzzprojects/Dapper-Plus#22]
Hello, 

I am trying dapper plus bulk inserts and noticed that the bulk insert seems to be failing now where it wasn't in the previous version. Error message is: "Update or insert of view or function 'DestinationTable' failed because it contains a derived or constant field."

Here is the code I am attempting to run:

DapperPlusManager.Entity<EntryRaw>().Table("dbo.EntryRaw").Identity(x => x.Id);
connection.BulkInsert(entitiesRaw);

I am not attempting to insert into views and I don't have a table/View called DestinationTable. Is this a known issues in this version of dapper plus?

**Comment by JonathanMagnan** [comment]
Hello @calemith ,

`DestinationTable` is the alias used by our script for the table/view `EntryRaw`.

Is `EntryRaw` a view? If yes, could you try a simple insert directly in SSMS (without our library) to see if you get the same error?

I currently believe that you currently try to perform an operation on a `read-only` view.

See: https://stackoverflow.com/a/25472496/5619143

Best Regards,

Jonathan

**Comment by calemith** [comment]
Hello Jonathan,

EntryRaw is a table. I tried a direct single insert through SSMS and it works fine. Is there an intermediary view that is used when performing the bulk insert?

**Comment by JonathanMagnan** [comment]
Nope,

Beside temporary table, we don't create anything.

That's a weird one,

Could you try with one row and if that fail, to use SQL Profiler to get the SQL executed and execute it directly in SSMS?

Perhaps that will point us in the right direction.

Best Regards,

Jonathan

**Comment by calemith** [comment]
hey John, 

Found the issue. Even though we transformed the list of objects to a new type, they were still the type that was named the same as a Read only- view we were using. 

We fixed it by doing a proper mapping to the correct type. thanks for your help!

**Comment by JonathanMagnan** [comment]
Oh, that's great ;)

Best Regards,

Jonathan
