### ISSUE TITLE
BulkInsert with array can fail with IndexOutOfRangeException

### ISSUE THREAD

**Issue by tedypranolo** [zzzprojects/Dapper-Plus#23]
```
void Main()
{
	using (var cnn = new SQLiteConnection("Data Source=G:\\test.sqlite"))
	{
		var test = (new[] { new Order(1), new Order(2) }).Take(1).ToArray();
		IReadOnlyList<Order> test2 = test;
		cnn.BulkInsert(test);
		cnn.BulkInsert(test2);
	}
}
public class Order
{
	public Order(int id)
	{
		Id = id;
	}
	public int Id { get; set; }
}
```

BulkInsert(test2) throws an exception because it uses the overload that takes an IEnumerable. Specifically it will fail on DapperPlusAction\Method\Execute.cs line 61.
              `  else if (DataSource.GetType().GetGenericArguments()[0] == typeof (object))`
Where it tries to get the generic argument but since it's actually an array, it doesn't have one.

BulkInsert(test) works because even though it is being passed an array, it will be converted into a list at DapperPlusActionSet\Constructor\Constructor.cs line 35.

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

Thank you for reporting this with all information required.

We will investigate it later today and try to provide a fix.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

The v1.3.7 has been released.

This issue should now be fixed.

Let me know if everything now work as expected.

Best Regards,

Jonathan

**Comment by tedypranolo** [comment]
That was fast. Thank you very much for the fix.
