### ISSUE TITLE
Support for Microsoft.Data.Sqlite.SqliteConnection

### ISSUE THREAD

**Issue by tedypranolo** [zzzprojects/Dapper-Plus#24]
For .net core I'm using Microsoft.Data.Sqlite instead of System.Data.Sqlite, I'm getting the exception : The Provider could not be resolved. You must explicity set the Provider

Is Microsoft.Data.Sqlite.SqliteConnection not supported?

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

Unfortunately no, the `Microsoft.Data.Sqlite` is not yet supported.

We will look at it and try to support it `ASAP`.

I will give you a status of our progress next Monday.

Best Regards,

Jonathan

**Comment by tedypranolo** [comment]
Thank you Jonathan. I look forward to the update. Hopefully the api is identical to System.Data.Sqlite.

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

The v1.3.10 has been released.

We added the first version of our support for Microsoft.Data.SQLite provider

I'm very sorry for missing to give you an update.

Could you try it and let me know about your result?

Best Regards,

Jonathan

**Comment by tedypranolo** [comment]
Thank you very much for the update. I will you know as soon as can update my code with the new version.

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
