### ISSUE TITLE
Unable to Merge XML columns

### ISSUE THREAD

**Issue by falvarez1** [zzzprojects/Dapper-Plus#27]
If I put the baseline config then my XML columns aren't mapping to my XElement Model properties.

Here's what my Mapper looks like:

```
DapperPlusManager.Entity<Members>().Table("Members")
                .Identity(x => x.MemberID)
                .Output("MetricsXML", "MetricsXML");   //added to test, but no luck
                .Map(member => member.MetricsXML.ToString(), "MetricsXML");   //added to test, but no luck
```

My Member model has a property of type XElement called MetricsXML.  This maps to a SQL table with an XML type column by the same name.  This mapping works using regular Dapper and other ORMs.

When using Output, Map or MapValue I get the exception: System.Exception: 'Cannot find the constant value from the expression.'

**Comment by JonathanMagnan** [comment]
Hello @falvarez1 ,

Thank you for reporting,

We will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @falvarez1 ,

The v1.3.13 has been released.

It looks that calculated value like this `member.MetricsXML.ToString()` was not supported (even if it was in our documentation).

It should now work fine.

Let me know if you still have the issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @falvarez1 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by falvarez1** [comment]
Thank you, works like a charm.
