### ISSUE TITLE
BulkInsert Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by myesn** [zzzprojects/Dapper-Plus#28]
Here is my code：

![image](https://user-images.githubusercontent.com/18598579/37551687-e92ae964-29df-11e8-8bc2-89ffb3edbeaa.png)

![image](https://user-images.githubusercontent.com/18598579/37551799-c9135b5e-29e2-11e8-8b45-5d9e3dcd01b5.png)

```c#
    class Program
    {
        static async Task Main(string[] args)
        {
            //var summary = BenchmarkRunner.Run<DapperTest>();

            Stopwatch sw = Stopwatch.StartNew();

            await DapperBulkInsert();

            sw.Stop();

            Console.WriteLine($"time consuming: {sw.ElapsedMilliseconds} ms\r\noperations done");

            Console.ReadKey();
        }

        static async Task DapperBulkInsert()
        {
            DapperPlusManager.Entity<UserToken>()
                .Table($"{nameof(UserToken)}s")
                .Identity(x => x.Id);

            Console.WriteLine("connect to database");
            using (var conn = new MySqlConnection("server=192.168.110.130;database=usercenterdb;uid=root;pwd=P@ssw0rd;charset='latin1';sslmode=none;"))
            {
                try
                {
                    await conn.OpenAsync();
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"error: {ex.Message}");
                    return;
                }

                Console.WriteLine("insert items");
                var rows = Enumerable.Range(0, 100).Select(x => new UserToken()
                {
                    Id = Guid.NewGuid(),
                    UserId = Guid.Parse("08d56d0b-f8fb-bed7-47d4-332e74ef4ef1")
                });

                try
                {
                    conn.BulkInsert(rows);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            }
        }
    }

    public class UserToken
    {
        public UserToken()
        {
            Expiration = LoginTime.AddHours(2d);
        }

        public Guid Id { get; set; }
        public DateTime Expiration { get; set; }
        public int LoginProvider { get; set; } = 0;
        public DateTime LoginTime { get; set; } = DateTime.Now;
        public Guid UserId { get; set; }
        public int State { get; set; } = 0;
    }
```

Then I run this program and get the following result：

![image](https://user-images.githubusercontent.com/18598579/37551706-84f2a88c-29e0-11e8-90c3-709379cc9d8f.png)

How can i fix it, tank you.

**Comment by JonathanMagnan** [comment]
Hello @myesn ,

Thank you for reporting. The MySqlConnector is not yet supported.

I believe there is an issue in our code that detects the current provider might be `https://www.nuget.org/packages/MySql.Data/` and then the error throws an error later instead of the traditional unsupported provider error.

We will look at the difficulty to support this new provider at the beginning of next week.

Best Regards,

Jonathan

**Comment by myesn** [comment]
Thank you for reply, I switch to Mysql.data(version: 8.0.10-rc), then program throw this error:
![image](https://user-images.githubusercontent.com/18598579/37648830-0a6075c6-2c6b-11e8-8a67-2e79dd448176.png)

**Comment by JonathanMagnan** [comment]
Hello @myesn ,

The v1.3.14 has been released.

A conditional compilation debug was missing and the wrong code was taken when reading MySQL.

Let me know if that works correctly with the new version.

Best Regards,

Jonathan

**Comment by myesn** [comment]
I use Z.Dapper.Plus(version: 1.3.14) and MySql.Data(version: 8.0.10-rc),but program also throw a error 
![image](https://user-images.githubusercontent.com/18598579/37691639-4092b194-2cee-11e8-88bb-661a23b6b00b.png)

![image](https://user-images.githubusercontent.com/18598579/37691635-3686ffa2-2cee-11e8-94a2-90062908ce94.png)

**Comment by JonathanMagnan** [comment]
Hello @myesn ,

Do you think you could provide us a project with this error?

That's normally due to something in your entities or your mapping so we cannot reproduce it on our side. You can send it in private here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by myesn** [comment]
Mail has been sent

**Comment by JonathanMagnan** [comment]
Hello @myesn ,

Unfortunately, our code will not work with the `Identity` as a GUID. Our code expects the column to be an identity column and not a GUID which causes the error.

You can make the code work with your code by removing it from the mapping:

```csharp
 DapperPlusManager.Entity<UserToken>()
                .Table($"{nameof(UserToken)}s");
```

Let me know if that answered your question correctly.

Best Regards,

Jonathan

**Comment by myesn** [comment]
It works now, thank you!
