### ISSUE TITLE
The DestinationTableName cannot be null or empty. You must specify a valid DestinationTableName.

### ISSUE THREAD

**Issue by andrewpropago** [zzzprojects/Dapper-Plus#33]
I'm receiving this error when attempting to use the BulkDelete operation on entity loaded classes.   Not sure what I'm doing wrong or what I'm missing at this point.

Dapper Version: 1.50.2
Dapper Plus Version: 1.3.18
Database: Sql Server 2014

```
            DapperPlusManager.Entity<Discount>().Table("Discount").Identity(x => x.DiscountId);
var manager = Manager<Part>.Instance;
                var query = manager.GetQuery(true, false).Where(a => a.Sku== sku);
                if (siteId.HasValue) {
                    query = query.Where(a => a.SiteId== siteId.Value);
                }

                if (companyId.HasValue) {
                    query = query.Where(a => a.CompanyId== companyId.Value);
                }

                if (vendorId.HasValue) {
                    query = query.Where(a => a.VendorId== vendorId.Value);
                }
                var part = query.FirstOrDefault();
                
                if (part != null) {
                    var priceList = part.PriceList.FirstOrDefault(a => a.CompanyPriceList.ISDEFAULT);
                    if (priceList != null)
                    {
                        var discountsToDelete = priceList.Discount.ToList();
                        var toInsert = new List<Discount>();
                        foreach (var priceBreak in priceBreaks) {
                            toInsert.Add(new Discount() {
                                PriceListId = priceList.PART_PRICELIST_ID,
                                Range = priceBreak.Quantity,
                                Type = ((char)priceBreak.Type).ToString(),
                                Discount = priceBreak.Discount,
                                RevenueCost= priceBreak.RevenueCost,
                                Created = DateTime.Now,
                                Modified = DateTime.Now,
                                IsDefault = priceBreak.IsDefault
                            });
                        }
                        var connection = UnityConfig.Container.Resolve<ArgosyEntities>().Database.Connection;
                        connection.BulkDelete<Discount>(discountsToDelete).BulkInsert<Discount>(toInsert);
}
```
Stack:

> System.Exception: The DestinationTableName cannot be null or empty. You must specify a valid DestinationTableName.
>    at Z.BulkOperations.BulkOperation.?()
>    at Z.BulkOperations.BulkOperation.?()
>    at Z.Dapper.Plus.DapperPlusAction.Execute()
>    at Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
>    at Z.Dapper.Plus.DapperPlusExtensions.BulkDelete[T](IDbConnection connection, String mapperKey, IEnumerable`1 items, Func`2[] selectors)
>    at Z.Dapper.Plus.DapperPlusExtensions.BulkDelete[T](IDbConnection connection, IEnumerable`1 items, Func`2[] selectors)
>    at Argosy.BusinessLogic.Services.Public.Managers.PartServiceManager.UpdatePartPriceBreaks(String sku, List`1 priceBreaks, Nullable`1 siteId, Nullable`1 companyId, Nullable`1 vendorId) in D:\development\Source\Repos\argosy\Argosy.BusinessLogic\Services\Public\Managers\PartServiceManager.cs:line 110

**Comment by JonathanMagnan** [comment]
Hello @andrewpropago ,

If I look at this line:

```csharp
onnection.BulkDelete<Discount>(discountsToDelete).BulkInsert<Discount>(toInsert);
```

You normally don't have to specify the generic type. I believe this line cause the issue since our library may find another mapping than `Discount` even if you forced it.

Do you think it could be possible to provide us a project example?

I will at the same time ask one of my developers tomorrow to try to reproduce it.

Best Regards,

Jonathan

**Comment by andrewpropago** [comment]
I figured out the issue, it's because entity framework loads the data w/ a proxy object.  We're converting slow entity interactions to dapper and dapper plus causing us to have a mix and match like this at times.

**Comment by andrewpropago** [comment]
Sorry, I've been on vacation.  

It would be great if we had an option whether it be a bool passed into the operation or a DapperPlusManager setting that could be enabled to use proxy discovery.  

Another possibility is just use the type from the generic call and ignore the object type all together.  In my example above the BulkDelete call would ignore the crazy proxy type all together and just assume it's type Discount.

Getting the underlying type for a proxy object is relatively simple ObjectContext.GetObjectType(dbEntitymodifiedEntry.Entity.GetType()) but I'm not sure the overall impact always running that line of code would have.

Thank You,
Andrew

**Comment by JonathanMagnan** [comment]
Hello @andrewpropago ,

When doing this request, we found out that we already coded in the past a logic to handle EF Proxy type. However, this logic had some flaw. We improve it to get the `.BaseType` which is what the `ObjectContext.GetObjectType` do under the hood.

Could you try the v1.3.22 and let me know if that has worked?

If you still have the issue, could you provide us a project with the issue.

Best Regards,

Jonathan

**Comment by andrewpropago** [comment]
I've been digging in a bit more, and the exact line that's causing the error seems redundant.

specifically it's this this.Current = (IEnumerable<TEntity>) items.ToList<TEntity>(); from the method below.


    ```
/// <summary>Constructor.</summary>
    /// <param name="oldActionSet">Set the old action belongs to.</param>
    /// <param name="mapperKey">The mapper key.</param>
    /// <param name="actionKind">The action kind.</param>
    /// <param name="items">The items.</param>
    /// <param name="selectors">A variable-length parameters list containing selectors.</param>
    public DapperPlusActionSet(BaseDapperPlusActionSet oldActionSet, string mapperKey, DapperPlusActionKind actionKind, IEnumerable<TEntity> items, params Func<TEntity, object>[] selectors)
    {
      this.ImportConfiguration(oldActionSet);
      if (items == null)
        return;
      this.Current = (IEnumerable<TEntity>) items.ToList<TEntity>();
      this.AddAction(mapperKey, actionKind, this.Current);
      if (selectors == null)
        return;
      List<List<object>> list = ((IEnumerable<Func<TEntity, object>>) selectors).Select<Func<TEntity, object>, List<object>>((Func<Func<TEntity, object>, List<object>>) (_param1 => this.Current.Select<TEntity, object>(_param1).ToList<object>())).ToList<List<object>>();
      this.AddAction(mapperKey, actionKind, (IEnumerable<object>) list);
    }
```

**Comment by JonathanMagnan** [comment]
So you still have an error?

Do you think you could provide a sample project (info@zzzprojects.com)? It will make easier for us then trying to reproducing this scenario.

**Comment by andrewpropago** [comment]
Yes, we're still having the error, I'm looking at your source vs the decompiled code and it seems like you don't need to .ToList() the items as it's already IEnumerable, which is what is causing the casting exception for reasons that are beyond me.

**Comment by JonathanMagnan** [comment]
The source are not up to date.

> which is what is causing the casting exception for reasons that are beyond me

It's a different exception than the first one? The initial exception was about the `DestinationTableName` and using a `ToList` doesn't cause this.

**Comment by andrewpropago** [comment]
You are correct, I'm bouncing between projects.  This is a different exception now, but still related to EntityFramework Proxy objects.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'ArgosyModel.ESM_CART' to type 'System.Data.Entity.DynamicProxies.ESM_CART_6C8EC2607204AA2EDA768B3EAC0A3F93BF30E697F726FA93E35F84B18141FDB0'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusActionSet`1..ctor(BaseDapperPlusActionSet oldActionSet, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1.BulkMerge[T](String mapperKey, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1.BulkMerge[T](IEnumerable`1 items, Func`2[] selectors)

**Comment by JonathanMagnan** [comment]
Thank, I believe I know how to easily reproduce it.

We will try it later today.

**Comment by JonathanMagnan** [comment]
Hello @andrewpropago ,

The v1.3.24 has been released.

We now call `GetObjectType` to get the type from the proxy type pretty much everywhere.

Let me know if everything is fixed.

Best Regards,

Jonathan

**Comment by andrewpropago** [comment]
Jonathan,
Thanks for all the help, that works perfectly now!

Andrew

**Comment by JonathanMagnan** [comment]
Hello @andrewpropago ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
