### ISSUE TITLE
Generic Dataservice via  Generics/Interfaces Throwing System.Exception Error

### ISSUE THREAD

**Issue by rslaine** [zzzprojects/Dapper-Plus#36]
My team would like to use Dapper-Plus using a standardized database interface to force everything to use "Id" when connecting to the DB.  The following will break throwing the error below on connection.BulkInsert(models).  This also occurs on BulkUpdate, which has a stacktrace below

System.Exception: 'Cannot find the constant value from the expression'

Calling Code:
```
   public class LocationBaseDataService : BaseDataService<LocationModel>
    {
        public LocationBaseDataService() : base("Locations"){}
    }
```

Create Portion of Base Class:
```

public class BaseDataService<TModel> : IDataService<TModel> where TModel : IUniqueModel
    {
        private readonly string _tableName;

        public BaseDataService(string tableName)
        {
            _tableName = tableName;
            DapperPlusManager.Entity<TModel>().Identity(x => x.Id).Table(tableName);
        }

        public int Create(TModel model)
        {
            using (var connection = new SqlConnection(AppConfigManager.GetDbConnectionString()))
            {
                connection.Open();
                var models = new List<TModel>() { model };
                connection.BulkInsert(models);
            }
            return model.Id;
 }
```

Can this error be fixed, or at least as a short term, enhance the error messages to show this scenario isn't supported?

**System Info:**
Dapper: 1.50.5
Z.Dapper.Plus : 1.3.22
DB: Azure DB
![dappererror](https://user-images.githubusercontent.com/2501000/44217023-73f3b680-a144-11e8-87b6-f6879f357441.PNG)

**Comment by JonathanMagnan** [comment]
Hello @rslaine ,

Is it possible to have a project sample or more information about it? Some class is missing from your example which will make harder to reproduce the issue.

You can send private code here info@zzzprojects.com

Best Regards,

Jonathan

**Comment by rslaine** [comment]
Sure, what class is missing that I can send you?  The interface of IUnqiueModel is the public Id.  The LocationModel just inherits that

**Comment by JonathanMagnan** [comment]
Hello @rslaine ,

Just to let you known that we successfully reproduced the issue. We are currently trying to fix to support it

**Comment by JonathanMagnan** [comment]
Hello @rslaine ,

The v1.3.23 has been released.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by rslaine** [comment]
1.3.23 has solved this issue for me.  Thank you!
