### ISSUE TITLE
BulkMerge Specify multiple columns

### ISSUE THREAD

**Issue by att1008** [zzzprojects/Dapper-Plus#38]
Hello

I had an exception when I executed this code.

>                 DapperPlusManager
>                    .Entity<CompanyInfo>()
>                    .Key(t => new { t.LinkId, t.Name });
>               try
>                {
>                    db.Database.Connection.BulkMerge(new CompanyInfo()
>                    {
>                        Name = "Betfair(英國)",
>                        LinkId = 2
>                    });
>                }
>                catch (Exception ex)
>                {
>
>                    throw;
>                }

I have specified more columns as key. I don't know if this is the right thing to do.

Error:

>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ';
>SELECT StagingTable.ZZZ_Index, 'UPDATE' AS $action, DestinationTable.`Id` A' at line 6

**Comment by JonathanMagnan** [comment]
Hello @att1008 ,

The `MariaDB` provider is still not in our supported list, that's probably why you get this error since our code failback to SQL Server provider by default.

Unfortunately, we have no short-term plan to support `MariaDB` at this moment ;(

Best Regards,

Jonathan

**Comment by att1008** [comment]
Hello @JonathanMagnan

Thank you very much for your answer. Your class library has helped me too much.

Best Regards,

att1008

**Comment by JonathanMagnan** [comment]
Great ;)

We will close this issue as answered, there is no short-term plan for supporting `MariaDB`.
