### ISSUE TITLE
The following type 'varchar' is not yet supported for the provider 'SQLiteMicrosoft'.

### ISSUE THREAD

**Issue by tedypranolo** [zzzprojects/Dapper-Plus#42]
I'm trying to insert to varchar column in Sqlite and was getting this error message 
`The following type 'varchar' is not yet supported for the provider 'SQLiteMicrosoft'.`
Is there a reason why varchar is not supported? Is there a workaround?

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

Thank you for reporting, we will look at it this Monday.

I see no reason why this column type is not supported.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

The v1.4.5 has been released. The support for this type has been added.

My developer has found a few more types that are still not supported on our side for `SQLiteMicrosoft`. We will work on it tomorrow and release a new version.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
No problem ;)

Just to let you know, the v1.4.6 has been released with additional type supported.

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

We will close this issue since it looks to be completed.

Best Regards,

Jonathan
