### ISSUE TITLE
Looking forward to support sqlite

### ISSUE THREAD

**Issue by liuzhenyulive** [zzzprojects/Dapper-Plus#43]
Thank for you created a so exciting tool,when i use the dapper-plus to connect sqlite, i meet the exception, i think this may because of dapper-plus not support sqlite.

```
Exception: The following type 'varchar ' is not yet supported for the provider 'SQLiteMicrosoft'. Please report the issue to our support team: info@zzzprojects.com
```
Looking forward to support it.

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @liuzhenyulive ,

Thank you for reporting.

We will look at this issue. `SQLiteMicrosoft` support has been added recently so perhaps we are still missing something.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @liuzhenyulive ,

The v1.5.8 has been released.

Could you try it and let me know if your issue is fixed. Your issue could maybe be different than the one we found.

Best Regards,

Jonathan

**Comment by liuzhenyulive** [comment]
thank you fix so qickly , I will try .

**Comment by liuzhenyulive** [comment]
yes,it been fixed, Thanks you so much.
