### ISSUE TITLE
How can I track failed rows when using BulkInsert/Merge/Update/Delete ?

### ISSUE THREAD

**Issue by raskolnikoov** [zzzprojects/Dapper-Plus#5]
When doing bulk CRUD operations I want to know what rows that did not get through and be able to handle these rows in some way, like logging out the row data.

**Comment by JonathanMagnan** [comment]
Hello @raskolnikoov ,

Unfortunately, this is a limitation of our library.

We perform operation in bulk (multiple rows at the same time), so we cannot know which rows doesn't satisfy a constraint, unique index, trigger, etc.

The only way to get this information is to failback and perform the operation one by one.

Unfortunately, this is something I don't think we could support.

Let me know if I answered correctly to your question.

Best Regards,

Jonathan

**Comment by raskolnikoov** [comment]
Thanks for the answer. I understand.
