### ISSUE TITLE
Possible to use DataTable on BulkMerge? 

### ISSUE THREAD

**Issue by raskolnikoov** [zzzprojects/Dapper-Plus#6]
Is it Possible to use DataTable on BulkMerge?

**Comment by JonathanMagnan** [comment]
Hello @raskolnikoov ,

Thank you for this suggestion. I believe that's not currently possible, but everything is already here to make it possible.

We will investigate this request this weekend and try to come with a solution on Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @raskolnikoov ,

The v1.0.17 has been released
https://www.nuget.org/packages/Z.Dapper.Plus/

The library is now compatible with DataTable

### Example
```csharp
var dt = new DataTable();
dt.Columns.Add("ID", typeof(int));
dt.Columns.Add("IntColumn", typeof(int));

for (int i = 0; i < 5; i++)
{
	dt.Rows.Add(DBNull.Value, i);
}

DapperPlusManager.Entity<DataTable>("Map_01")
	.Table("Left")
	.Identity("ID")
	.Map("IntColumn");

using (var conn = My.ConnectionFactory())
{
	conn.Open();
	
	conn.BulkInsert("Map_01", dt);
}
```

Let me know if you successfully implemented your scenario with a DataTable.

**Comment by raskolnikoov** [comment]
We are having some problems when we upgraded from version v1.0.15 to v1.0.17 that we are looking at. But our main problem now is that our trial license has expired and we are not 100% sure if we are going to go further with Z.DapperPlus. Is it possible to get a months trial license to continue our evaluation?

**Comment by JonathanMagnan** [comment]
Hello @raskolnikoov ,

The only way to extend your trial is by downloading the latest version (v1.0.17) which should have the trial enabled for March.

_You can extend your trial for several months by downloading the latest version once per month_

What is your issue with the v1.0,17?

**Comment by raskolnikoov** [comment]
![error](https://cloud.githubusercontent.com/assets/5316125/23658963/cf124e72-0344-11e7-84be-18064175b213.png)

**Comment by raskolnikoov** [comment]
It looks like the latest version you released has some funny characters in the code?

**Comment by JonathanMagnan** [comment]
We use an obfuscator, so yes, some funny characters could appears ;)

Could you also add the code for the mapping you used and the call to our library? That will help us to reproduce the issue

**Comment by raskolnikoov** [comment]
We found the problem. We where using .Output(x => x.prop) that was failing for us. So wrong config from us. The version is working now for us. :)
