### ISSUE TITLE
License ? Free/Pro clarification

### ISSUE THREAD

**Issue by yahorsi** [zzzprojects/Dapper-Plus#60]
Hi Guys,

As I understand you have 2 versions, free and pro. What is the diff and how I can use free version?
If I use nuget version - is it free or pro? And what exactly happens when trial expires.

Thank you

**Comment by JonathanMagnan** [comment]
Hello @yahorsi, 

Our paid library will give you access to our outstanding support! The license is perpetual and will work with any version released also, you will not need to update all of your projects. 

The free trial will give you access to the same features as the paid library. 

However, at the end of every month, your trial expires, you can download it again for the following month using the same method.

Here is the link to download the trial: https://dapper-plus.net/download 

Best regards, 

Jon

**Comment by yahorsi** [comment]
In other words, there is no free version? There is a paid version with trial period?

**Comment by JonathanMagnan** [comment]
Yes, there is a free trial. 

The trial expires every month.

However, you can extend your trial period by downloading it every month.

**Comment by JonathanMagnan** [comment]
hello @yahorsi 

How is your evaluation going?

People usually achieved performance improvement from 10x to 50x faster.

Did you successfully increase your application performance?

Looking forward to hearing from you,

Jon

**Comment by yahorsi** [comment]
Hello, we're now dropping the use of Dapper-Plus, used it in the very small project in the very limited amount, basically to update 3 tables. It turned out I misunderstood the licensing model. Though there is free license available that turned out to be incorrect.
