### ISSUE TITLE
Postgresql syntax error at or near 

### ISSUE THREAD

**Issue by buraksecer** [zzzprojects/Dapper-Plus#66]
Hello world!

I am using you for bulk insert operation but I updated the other day and now I started getting the error below.

Please support

My code

` DapperPlusManager.Entity<TEntity>().Table(typeof(TEntity).Name).Identity("Id").BatchTimeout(12000).BatchSize(50000);
            using (var connection = new NpgsqlConnection(_connectionString))
            { 
                connection.BulkInsert(entityList);
            }`
Error Message : ERROR SqlState: 42601 MessageText: syntax error at or near "ORDER" Position: 510 File: scan.lsd Line: 1150 Routine: scanner_yyerror}

Thank you!

**Comment by szymenn** [comment]
Also having the same issue, tried logging generated query, but I didn't understand what can be wrong with it, I'll try to find it in the logs and paste it later.

**Comment by JonathanMagnan** [comment]
Hello @buraksecer ,

Thank you for the code, we will try it and hope that it will reproduce the issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @buraksecer , @szymenn ,

Do you think you could provide a runnable project (you can send it in private here: info@zzzprojects.com)?

We tried again today but we fail to reproduce it.

Having a runnable code that already has the issue will allow us to fix this way faster.

**Comment by buraksecer** [comment]
@JonathanMagnan  hello again,

I sent example project. 

I hope , fixed my problem :)

Thanks for be interested 👍

**Comment by JonathanMagnan** [comment]
Hello @buraksecer ,

Thank you for the project, the v3.0.18 has been released.

Could you try it and let us know if everything is now fixed?

**Comment by buraksecer** [comment]
@JonathanMagnan  Of course i will try and i will share the results.

**Comment by buraksecer** [comment]
Thank You!

My problem fixed!

Congratulations! 💯

**Comment by JonathanMagnan** [comment]
Awesome @buraksecer ,

We are glad everything is working out for you!

Don't hesitate to contact us for any questions, issues or feedback!

Best regards,

Jon

**Comment by karolswdev** [comment]
This one could be closed, too :)
