### ISSUE TITLE
Support DB2

### ISSUE THREAD

**Issue by raskolnikoov** [zzzprojects/Dapper-Plus#7]
Hi, we use today dapper plus with our sql servers with great results. We also have a AS/400 DB2 database that is pretty vital in our infrastructure that we would like to do bulk operations to. Is this something you could support?

**Comment by JonathanMagnan** [comment]
Hello @raskolnikoov ,

Our main focus is currently trying to support .NET Core/EF Core at this moment.

However, in a few months, we will for sure investigate more this request.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @raskolnikoov ,

We will close this request on GitHub since I don't think we will support `DB2` in 2018 either.

We have added this request in our `pool` list of features so we will be able to track from here instead.

Best Regards,

Jonathan
