### ISSUE TITLE
Oracle Client  - The Provider could not be resolved. You must explicitly set the Provider.

### ISSUE THREAD

**Issue by vteixeira87** [zzzprojects/Dapper-Plus#71]
I'm trying to test the library and I'm taking this error when running BulkInsert.

Follow my code

```csharp
private OracleConnection _conn;
      

        public OcupacaoDb()
        {
            if (_conn != null) return;

            var strConnection = ConfigurationManager.ConnectionStrings["Oracle"].ConnectionString;

            _conn = new OracleConnection { ConnectionString = strConnection };

            if (_conn.State == ConnectionState.Closed)
                _conn.Open();
        }


  using (var bulk = new BulkOperation<OcupacaoOracle>(_conn))
                {
                    // easy to use
                    bulk.DestinationTableName = "Ocupacao";

                    bulk.BulkInsert(ocupacaoList);
                }
```

**Comment by JonathanMagnan** [comment]
Hello @vteixeira87 ,

Could you let us know exactly which `Oracle` package you are using?

Our library supports Oracle, so we are not sure yet why you are getting this error.

Best Regards,

Jon

**Comment by vteixeira87** [comment]
Hello

I'm using
System.Data.OracleClient

I didn't see if there is any place to map between the DTO and the table, but my Dto has the same properties as the table and their names are the same too.

**Comment by JonathanMagnan** [comment]
Hello @vteixeira87 ,

Is there a reason why you currently use a custom package: https://www.nuget.org/packages/System.Data.OracleClient/ instead of the official one? https://www.nuget.org/packages/Oracle.ManagedDataAccess/

From what it looks, the package you are currently using is no longer supported.

**Comment by vteixeira87** [comment]
I'm on a legacy project and it is quite extensive, the exchange of packages is unviable at the moment, unfortunately.

But the package serves us well, in all necessary operations.

**Comment by vteixeira87** [comment]
Actually what we use is this

https://docs.microsoft.com/en-us/dotnet/api/system.data.oracleclient?view=dotnet-plat-ext-3.1

**Comment by JonathanMagnan** [comment]
Unfortunately, we already discussed in the past about not supporting the package made by Microsoft since even themselves don't longer support it.

So, unfortunately, It will not be possible to use our library with this legacy package.

**Comment by vteixeira87** [comment]
Okay, thank you so much for returning
