### ISSUE TITLE
It is not possible to disaple auditing for table

### ISSUE THREAD

**Issue by ElenaShlykova** [zzzprojects/Dapper-Plus#76]
Hello!
 I have a main table that should be audited. This table has one-to-many reference to a child table and changes in the child table should **not** be audited.
I update data in these tables in the single query with BulkUpdate command.
I added `AuditMode(AuditModeType.ExcludeAll)` to the mapping for the child table but I still receive AuditEntry for the child table just without values. 
I need to completely exclude the child table from auditing, is it possible?

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

We will look at it as it seems true to be currently impossible or very hard.

If you need a very quick solution, you can try this one, I'm not sure if it will have a side impact however:

```csharp
DapperPlusManager.Entity<YouEntityTypeToExclude>().UseBulkOptions(x => x.BulkOperationExecuting = operation => operation.UseAudit = false);
```

Best Regards,

Jon

**Comment by ElenaShlykova** [comment]
Thank you! It works

**Comment by JonathanMagnan** [comment]
Awesome @ElenaShlykova 

Don't hesitate to contact us with any questions or further assistance!

Best regards,

Jon
