### ISSUE TITLE
BulkUpdate: Illegal mix of collations with MySqlConnector driver

### ISSUE THREAD

**Issue by SockeThe2nd** [zzzprojects/Dapper-Plus#77]
Hi, I am using the BulkUpdateAsync method to update rows by id (string) with the MySqlConnector driver.

However I get an `"Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='"`-Error when using the Bulk-Operations. However single updates or updates by non-string columns in bulk seem to work.

**Comment by JonathanMagnan** [comment]
Hello @SockeThe2nd ,

Thank you for reporting, we will look if we can reproduce it.

Best Regards,

Jon

**Comment by SockeThe2nd** [comment]
Hi, thank you for the quick response.

I also tested the Connector/Net MySql.Data driver with the same error message.

**Comment by JonathanMagnan** [comment]
Hello @SockeThe2nd ,

My developer didn't succeed to reproduce it finally.

However, he provided me this answer: https://ask4knowledgebase.com/questions/1008287/illegal-mix-of-collations-mysql-error

From what I understand, it seems to only happen when processing a lot of data.

Let me know if that helped a little bit
