### ISSUE TITLE
The Provider could not be resolved. You must explicity set the Provider.

### ISSUE THREAD

**Issue by PedroHFranco** [zzzprojects/Dapper-Plus#8]
I'm making a synchronization application, from Firebird to SQL Server. And I'm using BulkInsert from Dapper Plus.

```csharp
var fbClient = new FirebirdConnect();
using (var source = fbClient.GetConnection())
{

    if (source.State == ConnectionState.Closed)
        source.Open();

    var sqlClient = new AzureConnect();
    using (var target = sqlClient.GetConnection())
    {
        if (target.State == ConnectionState.Closed)
            target.Open();

        var lastUpdate = connection.Query<DateTime>($"select coalesce((select max(DateSyncTarget) from {metadados.TargetName}), getdate()-10000) LastUpdate").ToList();

        var resultSource = source.Query<MyClass>("select * from MyClass");

        target.BulkInsert(resultSource.Where(w => w.Data > lastUpdate[0]));

        var resultTargert = target.Query<MyClassSource>("select * from MyClass")

        source.BulkInsert(resultTargert.Where(w => w.Data > lastUpdate[0]));//Error here

    }
}
```

Everything happens well when I consult the source to do the insertion in the target.

But when I query on target to insert into source, it is giving the following error:

The Provider could not be resolved. You must explicity set the Provider.
Some idea of ​​what causes the error?

Full stack:
   em ..(BulkOperation )
   em ..(BulkOperation )
   em Z.BulkOperations.BulkOperation.BulkInsert()
   em Z.Dapper.Plus.DapperPlusAction.Execute()
   em Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
   em Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
   em Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
   em Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, String mapperKey, T item, Func`2[] selectors)
   em Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, T item, Func`2[] selectors)
   em Project.Plugins.Utils.Extensions.CommandExtensions.InsertSource[T](IDbConnection connection, IEnumerable result) na D:\Projetos\Project-API-Cloud\project-etl\Project.Plugins.Utils\Extensions\CommandExtensions.cs:linha 52
   em Autorizacoes.ERP.LIBSENHA.JobAutorizacoes.Execute(IJobExecutionContext context) na D:\Projetos\Project-API-Cloud\Project-etl\Autorizacoes\JobAutorizacoes.cs:linha 105

**Comment by JonathanMagnan** [comment]
Hello @PedroHFranco ,

Could you give me information about how to use AzureConnect? It looks there is more than one solution that provides this class name. So I don't know which one to use to replicate and fix this issue.

Best Regards,

Jonathan

**Comment by PedroHFranco** [comment]
Hello!!

@JonathanMagnan My AzureConnect, is just an Sql Server connection that connect on Azure.

```
    public class AzureConnect : SqlConnect
    {
        public override SqlConnection GetConnection()
        {
            var dataBaseString = "Server=server;Initial Catalog=ReceituarioHomolog;Persist Security Info=False;User ID=user;Password=pass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            var dataBaseConnect = new SqlConnection(dataBaseString);

            if (dataBaseConnect.State == ConnectionState.Closed)
                dataBaseConnect.Open();

            return dataBaseConnect;
        }
    }
```
The problem is to BulkInsert on source.
To connect on Source i'm returning and DbConnection cause the client can use two types of Database.

    ```
    public DbConnection GetConnection()
        {
            var settings = Settings.Data.Connections.First(f => f.ERP.Equals("AgriBussines"));
            if (settings.ConnectionType.Equals("Oracle"))
            {
                var dataBaseString = string.Format(@"Data Source={0};User id={1}; Password={2}; enlist=false; pooling=false;", settings.Database, settings.Usuario, settings.Password);
                var dataBaseConnection = new OracleConnection(dataBaseString);

                OracleConnection.ClearPool(dataBaseConnection);

                if (dataBaseConnection.State == ConnectionState.Closed)
                    dataBaseConnection.Open();

                return dataBaseConnection;
            }
            else
            {
                var dataBaseString = string.Format(@"User={0};
                                                       Password={1};
                                                       Database={2};
                                                       Port=3050;Dialect=3", settings.Usuario, settings.Password, settings.Database);

                var dataBaseConnection = new FbConnection(dataBaseString);
                if (dataBaseConnection.State == ConnectionState.Closed)
                    dataBaseConnection.Open();

                return dataBaseConnection;
            }
            
        }
```

**Comment by JonathanMagnan** [comment]
Hello @PedroHFranco ,

Thank you for the additional info. I thought the problem was on the target database and forget to check the source.

Currently, we support Oracle but not Firebird provider which probably causes the issue.

Unfortunately, in the next few weeks, our priority is already on supporting .NET Core for all our products, so I don't think honestly, we will have the time to support Firebird.

Best Regards,

Jonathan

**Comment by PedroHFranco** [comment]
@JonathanMagnan 

Could u give me some direction?
And i can contribute making this implementation, to suport Firebird.

**Comment by JonathanMagnan** [comment]
Hello @PedroHFranco ,

We will try to take time and investigate this provider this weekend to make sure if it's possible or not to make optimization. Perhaps, we can start by supporting a few features of our library to make it compatible with your requirement and complete it next month.

Which version of Firebird are you using?

I will give you more information on Monday.

Best Regards,

Jonathan

**Comment by PedroHFranco** [comment]
@JonathanMagnan 

Thank's for your asnwer.

I'm using Firebird 2.1

**Comment by JonathanMagnan** [comment]
Hello @PedroHFranco ,

We started to make some research on this provider. We are not sure yet what can of performance improvement our library will be able to bring.

We will first try to implement our library this week with some basic statement, and we will make sure we provide the best performance as possible in another phase.

I will keep you updated. I believe the first phase will be completed this week.

Best Regards,

Jonathan

**Comment by PedroHFranco** [comment]
Solved in new version.
