### ISSUE TITLE
Dapper Plus Support for Other NodaTime Types.

### ISSUE THREAD

**Issue by carlos0202** [zzzprojects/Dapper-Plus#88]
Hi guys,

Thanks for all the support previously adding support for LocalDateTime type from NodaTime. It would be very helpful for our project if we can get some other NodaTime Types added to support (LocalDate and Instant) to fit our needs while using the library. 

Right now, I'm facing a null value being sent to the database while using other types than LocalDateTime that was added from [this](https://github.com/zzzprojects/Dapper-Plus/issues/78) issue .

Can we have the other types I mentioned (I know that is hard to have all NodaTime types) or have a way to add own type mappings? 

Thanks in advance for all your help.

**Comment by JonathanMagnan** [comment]
Hello @carlos0202 ,

Since this time, we added a new method that let you add any type that we do not support yet:

such as:

```csharp
DapperPlusManager.AddCustomSupportedType(typeof(NodaTime.LocalDateTime));
DapperPlusManager.AddCustomSupportedType("NodaTime.LocalDateTime");
```

Could you try it and let us know if that worked?

Best Regards,

Jon

**Comment by carlos0202** [comment]
> ```cs
> DapperPlusManager.AddCustomSupportedType(typeof(NodaTime.LocalDateTime));
> ```

Hi Jon,

I've tried adding that line of code but Method AddCustomSupportedType is missing. Since which version is this method available?

**Comment by JonathanMagnan** [comment]
Hello @carlos0202 ,

The method has been added in the latest version released 5 days ago.

So v4.0.1, just right in time for your question ;)

**Comment by carlos0202** [comment]
> Hello @carlos0202 ,
> 
> The method has been added in the latest version released 5 days ago.
> 
> So v4.0.1, just right in time for your question ;)

Hi, 

Jonathan, I tested with that version and it worked. Closing this, thanks for your help.
