### ISSUE TITLE
DateTime overflow

### ISSUE THREAD

**Issue by PedroHFranco** [zzzprojects/Dapper-Plus#9]
Hello,

Today i got this error with datetime.

I'm making a simple insert with Bulk, and gotting this execption

> SqlDateTime overflow must be between 1/1/1753 12:00:00 AM and 31/12/9999 11:59:59 PM.

StackTrace: 

>   em System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
>    em System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    em System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    em System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    em System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    em Z.BulkOperations.SqlActionExecutor.(SqlCommand , BulkOperation , Int32 )
>    em Z.BulkOperations.SqlActionExecutor.(DbCommand , BulkOperation , Int32 )
>    em Z.BulkOperations.SqlActionExecutor.( , DbCommand )
>    em ..(List`1 )
>    em Z.BulkOperations.SqlProvider.(List`1 )
>    em ..(BulkOperation )
>    em Z.BulkOperations.BulkOperation.BulkInsert()
>    em Z.Dapper.Plus.DapperPlusAction.Execute()
>    em Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
>    em Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
>    em Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
>    em Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, String mapperKey, T item, Func`2[] selectors)
>    em Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, T item, Func`2[] selectors)
>    em Project.Plugins.Utils.Extensions.CommandExtensions.Insert[T](IDbConnection connection, IEnumerable result) na D:\Projetos\Project-API-Cloud\Project-etl\Project.Plugins.Utils\Extensions\CommandExtensions.cs:linha 88
>    em SolicitacoesAutorizacao.ERP.PEDSENHA.JobSolicitacoesAutorizacao.Execute(IJobExecutionContext context)

I'm trying to insert this dates:

![bulkdateerror](https://cloud.githubusercontent.com/assets/10779853/26636217/6f9ca578-45f2-11e7-9748-83cb2143c0d6.png)

Obs.: Yestarday was working fine.

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @PedroHFranco ,

Are you sure this date was the same yesterday? Perhaps the value was null or inside a valid range?

I don't think this issue is related to our library. You currently try to insert a `01/01/0001` date time value which is in the valid range supported by SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql

Let me know if that helped you to understand the issue or you need more information.

Best Regards,

Jonathan

**Comment by PedroHFranco** [comment]
Hi @JonathanMagnan 

This was my mistake,

This times i got an null Datetime,

A simple '?' on my variable solve this problem.

Thank you again for ur faster asnwer.
