### ISSUE TITLE
BulkActionAsync with UseBulkOptions

### ISSUE THREAD

**Issue by jakehockey10** [zzzprojects/Dapper-Plus#91]
Hello,

I'm currently running a command like this:

``` csharp
connection
      // Want to make sure that we only insert what we don't already have
      .UseBulkOptions(options => options.InsertIfNotExists = true)   
      // Attempt to insert all sensor readings
      .BulkInsert(sensorReadings);
```

I would like to make this an asynchronous operation.  However, I can't figure out how to choose the `InsertIfNotExists = true` option when using `connection.BulkActionAsync(x => ...)`.  `UseBulkOptions` doesn't seem to be a method I can use any more inside of the `Action` I pass into `BulkActionAsync`.

Is there a way to do this with `BulkActionAsync`?  Should I avoid just using `Task.Run(() => ...)`?

**Comment by JonathanMagnan** [comment]
Hello @jakehockey10 ,

Thank you for reporting, we indeed seem to miss something here.

We will look at it.

Best Regards,

Jon

**Comment by jakehockey10** [comment]
@JonathanMagnan Thank you so much!  I have scheduled an upgrade for our team and I will let you know how that goes.  Thank you very much for the prompt response and adjusting the API for us.

**Comment by JonathanMagnan** [comment]
Awesome @jakehockey10 

I will be looking forward to hearing from you!

**Comment by jakehockey10** [comment]
@JonathanMagnan we are good to go.  I appreciate everything!
