### ISSUE TITLE
An error occurred while using the bulk insert operation.

### ISSUE THREAD

**Issue by coolsharma97** [zzzprojects/Dapper-Plus#95]
I am using bulk insert operation it works correctly but sometimes it will throw **Object reference not set to an instance of an object**.
I don't know why it is throwing if I try again with the same data it works perfectly.

**Comment by JonathanMagnan** [comment]
Hello @coolsharma97 ,

Do you have a stack trace, are you able to "reproduce" it in a standalone project?

Obviously, I can be wrong in my hypothesis as some information is currently missing but I believe your issue happens because you map multiple time your entity.

Mapping Doc: https://dapper-plus.net/getting-started-mapping

For example, you use the `Global Context Mapping` but you remap it in one of your methods every time. So you keep overridden the mapping while another thread currently uses this mapping which could lead to this error.

If you really need to map inside a method, consider looking at the `Instance Context Mapping` which allows you to change the dynamic on the fly.

Let me know more about your issue and we will try our best to help you.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @coolsharma97 ,

Since our last conversation, we haven't heard from you!

Were you able to discover what caused the issue?

Don't hesitate to provide more information so that we can assist you better!

Best regards,

Jon

**Comment by coolsharma97** [comment]
Hello @JonathanMagnan 
Thanks for you assist
I am attaching a text file that has a demo code. 
Please see this
[demmocode.txt](https://github.com/zzzprojects/Dapper-Plus/files/6716245/demmocode.txt)

**Comment by JonathanMagnan** [comment]
Thank you @coolsharma97 ,

What's the reason you are currently adding the mappings and removing it in your `DocumentDetailsBulkInsert` method?

This looks a little bit weird for me and probably what's causing your issue.

## Solution 1

As previously said, one way to solve it is using an `Instance Context Mapping` like this example: https://dotnetfiddle.net/WHSCTW

In your case, it should look like this:

```csharp
// The connection and transaction is passed to this new context instance
var context = new DapperPlusContext(connection, transaction);

context.Entity<DocumentDetails>().Table("DocumentDetails").Identity(x => x.DocumentId);
// ...code mapping...

var result = context.BulkInsert(objectToInsert)
// ...code insert...
```

In addition, you will not have anymore to use the `RemoveEntity` method as the mapping will be disposed with the context disposed.

## Solution 2

Using a mapping key can also work.

The mapping will need to be moved somewhere that's called only once (on application startup for example).

```csharp
// Somewhere in your code that's called only once
const string MappingKey = "ForDocumentDetailsBulkInsert";
DapperPlusManager.Entity<DocumentDetails>(MappingKey).Table("DocumentDetails").Identity(x => x.DocumentId);

// in your DocumentDetailsBulkInsert method
var result = transaction.BulkInsert(MappingKey, objectToInsert)
```

Again, the `RemoveEntity` code will need to be removed. An entity can be mapped multiple time for different mapping key and this mapping will only be used when you pass the mapping key.

## Conclusion

Both solutions work very well, it really depends on your preference or other requirements you have.

Let me know if that helped you to fix this issue or you need more help with this.

**Comment by coolsharma97** [comment]
Hi @JonathanMagnan 
Apologies for the late reply. We are checking on this.
We will let you know if any errors occurred.
Thanks for your support.

**Comment by JonathanMagnan** [comment]
Awesome @coolsharma97 !

Don't hesitate to contact us with any questions, issues, or feedback!

Best regards,

Jon

**Comment by coolsharma97** [comment]
HI @JonathanMagnan 
We tried your suggestion (Solution 1) but we are getting the below error :

**An error occurred while retrieving the InformationSchemaTable information. See the inner exception for details.**

stack trace for the above error is given below :

 at Z.BulkOperations.BulkOperation.()   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
   at Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
   at Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(DapperPlusContext context, IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusContext.BulkInsert[T](String mapperKey, T item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusContext.BulkInsert[T](T item, Func`2[] selectors)
   at DataAccessLayer.Context.DocumentDetailsContext.DocumentDetailsBulkInsert

And I am also attaching the demo code. Please review it and let us know where we are doing wrong.

Thanks

[demo code 2.txt](https://github.com/zzzprojects/Dapper-Plus/files/6726605/demo.code.2.txt)

**Comment by JonathanMagnan** [comment]
Hello @coolsharma97 ,

What's the `Inner Exception` message?

The current errors happen when we try to find information about one of your 3 tables but without the inner exception, it kind of hard to know what's exactly your error.

I believe that's because one of your entity have a table with a different name but I might be wrong. Not all your entity is mapped so I'm not sure if there is one missing or not.

**Comment by coolsharma97** [comment]
Hello @JonathanMagnan 

Inner Exception is given below : 
**ExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.**

Please let me know if any other things you want from my side.

Thanks for helping us.

**Comment by JonathanMagnan** [comment]
Hello @coolsharma97 ,

My developer and I took some time to try to reproduce it. We did all kind of method chaining but never got any issue with the `Transaction`. We also double checked all our code and everything time a `Connection` is copied/specified, the `Transaction` is also copied/specified.

Is it possible for you to provide a runnable project with the minimum code && the table script creation? You can send it in private here: info@zzzprojects.com

Unfortunately, it looks like the puzzle piece is still missing to allow us to reproduce it and fix this issue.

**Comment by coolsharma97** [comment]
Hello @JonathanMagnan 
Okay, We will share a small project with your team.

Thanks

**Comment by JonathanMagnan** [comment]
Hello @coolsharma97 ,

Since our last conversation, we haven't heard from you!

Don't hesitate to share your runnable project with our support team info@zzzprojects.com 

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again!

A simple reminder that we are here to assist you :)

Feel free to provide a runnable project to our support team info@zzzprojects.com 

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @coolsharma97 ,

Since we haven't heard back, we will close this issue. 

Feel free to contact us at info@zzzprojects.com once you can provide more information. 

Best regards,

Jon
